In [5]:
import numpy as np

# sigmoid 구현
def sigmoid(x):
    return 1/(1 + np.exp(-x))

def identity_function(x):
    return x

def init_network():
    network = {}
    network['W1'] = np.array([[0.1, 0.3, 0.5], [0.2, 0.4, 0.6]])
    network['b1'] = np.array([0.1, 0.2, 0.3])
    network['W2'] = np.array([[0.1, 0.4], [0.2, 0.5], [0.3, 0.6]])
    network['b2'] = np.array([0.1, 0.2])
    network['W3'] = np.array([[0.1, 0.3], [0.2, 0.4]])
    network['b3'] = np.array([[0.1, 0.2]])

    return network

# 순전파 구현
def forward(network, x):
    W1, W2, W3 = network['W1'], network['W2'], network['W3']
    b1, b2, b3 = network['b1'], network['b2'], network['b3']

    a1 = np.dot(x, W1) + b1
    z1 = sigmoid(a1)
    a2 = np.dot(z1, W2) + b2
    z2 = sigmoid(a2)
    a3 = np.dot(z2,a2) + b3
    y = identity_function(a3)

    return y

network = init_network()
x = np.array([1.0, 0.5])
y = forward(network, x)
print(y)

[[1.35927254 1.45927254]]


## 소프트맥스 함수 구현 시 주의점
지수 함수는 쉽게 큰 값을 내뱉기 때문에 오버플로 문제가 발생합니다.

$y_{k} = \frac{exp(a_{k})}{\sum_{i=1}^{n}exp(a_{i})} = \frac{C exp(a_{k})}{C \sum_{i=1}^{n}exp(a_{i})} = \frac{exp(a_{k} + \log(C))}{\sum_{i=1}^{n}exp(a_{i} + \log(C))} = \frac{exp(a_{k} + C')}{\sum_{i=1}^{n}exp(a_{i} + C')}$

이 식이 말하는 것은 소프트맥스의 지수 함수를 계산할 때 어떤 정수를 더하거나 빼도 결과는 바뀌지 않는다는 것 입니다. 오버플로를 막을 목적으로 입력 신호 중 최댓값을 이용합니다.

In [8]:
a = np.array([1010, 1000, 990])
print(np.exp(a) / np.sum(np.exp(a)))

max_a = np.max(a) # 최댓값 1010
a -= max_a

print(a)
print(np.exp(a) / np.sum(np.exp(a))) # 오버플로 문제 해결

[nan nan nan]
[  0 -10 -20]
[9.99954600e-01 4.53978686e-05 2.06106005e-09]


C:\Users\jinho\AppData\Local\Temp\ipykernel_24076\3950884165.py:2: RuntimeWarning: overflow encountered in exp
  print(np.exp(a) / np.sum(np.exp(a)))
C:\Users\jinho\AppData\Local\Temp\ipykernel_24076\3950884165.py:2: RuntimeWarning: invalid value encountered in divide
  print(np.exp(a) / np.sum(np.exp(a)))


In [ ]:
def softmax(a):
    max_a = np.max(a)
    exp_a = np.exp(a - max_a)
    sum_exp_a = np.sum(exp_a)

    return exp_a / sum_exp_a